<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HYL-777648" name="com.hyland.IT.tests.OCIntegrationTest" tests="20" failures="4" timestamp="17 Jul 2020 16:56:21 GMT" time="41.717" errors="0">
  <testcase name="PASSED --&gt; File Name : DeficiencyServices2.yaml; End Point : /" time="3.330" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices3.yaml; End Point : /docLocking" time="0.648" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="FAILED --&gt; File Name : TaskListServices.yaml; End Point : /encounter" time="4.461" classname="com.hyland.IT.tests.OCIntegrationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [201] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.hyland.IT.tests.OCIntegrationTest.ocRestAPITest(OCIntegrationTest.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- FAILED -> File Name : TaskListServices.yaml; End Point : /encounter -->
  <testcase name="PASSED --&gt; File Name : DeficiencyServices.yaml; End Point : /" time="2.893" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices3.yaml; End Point : /getDictationDocTypes/{facility}" time="1.613" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="FAILED --&gt; File Name : DeficiencyServices2.yaml; End Point : /deficiencyDocInfo" time="1.243" classname="com.hyland.IT.tests.OCIntegrationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [201] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.hyland.IT.tests.OCIntegrationTest.ocRestAPITest(OCIntegrationTest.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- FAILED -> File Name : DeficiencyServices2.yaml; End Point : /deficiencyDocInfo -->
  <testcase name="PASSED --&gt; File Name : DeficiencyServices2.yaml; End Point : /getDictationJobIds/{encounter}" time="0.704" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices3.yaml; End Point : /getDictationJobIds/{encounter}" time="0.652" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices3.yaml; End Point : /getDocTypesForDefType/{facility}" time="1.050" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices.yaml; End Point : /getDictationJobIds/{encounter}" time="0.685" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices.yaml; End Point : /getDocTypesForDefType/{facility}" time="0.969" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="FAILED --&gt; File Name : DeficiencyServices3.yaml; End Point : /deficiencyDocInfo" time="0.639" classname="com.hyland.IT.tests.OCIntegrationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [201] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.hyland.IT.tests.OCIntegrationTest.ocRestAPITest(OCIntegrationTest.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- FAILED -> File Name : DeficiencyServices3.yaml; End Point : /deficiencyDocInfo -->
  <testcase name="FAILED --&gt; File Name : DeficiencyServices.yaml; End Point : /deficiencyDocInfo" time="0.665" classname="com.hyland.IT.tests.OCIntegrationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [201] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.hyland.IT.tests.OCIntegrationTest.ocRestAPITest(OCIntegrationTest.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- FAILED -> File Name : DeficiencyServices.yaml; End Point : /deficiencyDocInfo -->
  <testcase name="PASSED --&gt; File Name : TaskListServices.yaml; End Point : /tasklist" time="13.123" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices2.yaml; End Point : /docLocking" time="0.772" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices.yaml; End Point : /docLocking" time="0.679" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices3.yaml; End Point : /" time="3.002" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices2.yaml; End Point : /getDictationDocTypes/{facility}" time="1.782" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices2.yaml; End Point : /getDocTypesForDefType/{facility}" time="1.200" classname="com.hyland.IT.tests.OCIntegrationTest"/>
  <testcase name="PASSED --&gt; File Name : DeficiencyServices.yaml; End Point : /getDictationDocTypes/{facility}" time="1.607" classname="com.hyland.IT.tests.OCIntegrationTest"/>
</testsuite> <!-- com.hyland.IT.tests.OCIntegrationTest -->
